## Begining in Pytorch

Pytorch 0.4.0

Pytorch是由Facebook 深度学习lab开发。前身为Torch，但是由于Torch使用的是lua语言，导致用户数量较少。因此Facebook后续推出基于Python的Pytorch版本。Pytorch和TensorFloat在设计上具有很多相似之处。但是Pytorch对用户而言更加友好，是一个非常火热的深度学习框架。<br>
Pytorch的特殊数据类型有Tensor和Variable两种。<br>

## Pytorch的Tensor类型

In [1]:
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from six.moves import xrange

创建一个Tensor变量

In [2]:
x = torch.Tensor(3, 2)
print(x)


tensor([[-1.3253e+07,  4.5678e-41],
        [-1.3253e+07,  4.5678e-41],
        [-2.6297e+04,  4.5678e-41]])


创建一个随机Tensor变量

In [3]:
x = torch.rand(3, 2)
print(x)


tensor([[ 0.1107,  0.7850],
        [ 0.5947,  0.9395],
        [ 0.8935,  0.0424]])


创建一个全1/全0/对角 Tensor变量

In [4]:
x = torch.ones(3, 2)
print(x)
x = torch.zeros(3, 2)
print(x)
x = torch.eye(3, 3)
print(x)


tensor([[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]])
tensor([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])


加(减) 乘(除) 矩阵乘法 运算

In [5]:
# 加
x = torch.eye(3, 2)
y = torch.ones(3, 2)
print(x + y == x.add(y))
print(x / y == x.mul(y))
y = torch.ones(2, 3)
print(x.mm(y))


tensor([[ 1,  1],
        [ 1,  1],
        [ 1,  1]], dtype=torch.uint8)
tensor([[ 1,  1],
        [ 1,  1],
        [ 1,  1]], dtype=torch.uint8)
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 0.,  0.,  0.]])


x.add\_(y) = x+y and x+=y <br>
类似的有： add\_ mul\_ abs\_等

In [6]:
x = torch.eye(3, 2)
y = torch.ones(3, 2)
print(x)
x.add_(y)
print(x)


tensor([[ 1.,  0.],
        [ 0.,  1.],
        [ 0.,  0.]])
tensor([[ 2.,  1.],
        [ 1.,  2.],
        [ 1.,  1.]])


reshape

In [7]:
print(x.size())
x = x.view(1, -1)
print(x.size())


torch.Size([3, 2])
torch.Size([1, 6])


Torch Tensor与Numpy Array相互转换

In [8]:
import numpy as np

x = np.eye(3, 2)

# numpy -> tensor
y = torch.from_numpy(x)
print(y)

# tensor -> numpy
y = y.numpy()
print(y)


tensor([[ 1.,  0.],
        [ 0.,  1.],
        [ 0.,  0.]], dtype=torch.float64)
[[1. 0.]
 [0. 1.]
 [0. 0.]]


Tensor变量在GPU，CPU的转换

In [9]:
# 判断电脑是否支持GPU运算
print(torch.cuda.is_available())

# 将Tensor送人用GPU中
x = torch.eye(3, 2).cuda()
y = torch.ones(3, 2).cuda()
print(x + y)

# 将cuda.Tensor返回到CPU中
print(x.cpu())


True
tensor([[ 2.,  1.],
        [ 1.,  2.],
        [ 1.,  1.]], device='cuda:0')
tensor([[ 1.,  0.],
        [ 0.,  1.],
        [ 0.,  0.]])


## Pytorch的Variable变量

In [10]:
from torch.autograd import Variable

# 创建一个Variable变量
# requires_grad=True表明：该变量是可导的，也就是说它可以作神经网络中的参数，用于自学习
x = Variable(torch.ones(2,2), requires_grad=True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


定义多个函数<br>
y1\ =\ 2\*x\*x
y2\ =\ mean(y1)
，并求导

In [11]:
y1=2*x**2
print(y1)

y2=y1.mean()

# 注意：最后一个输出必须为一个标量
y2.backward() # 标记求导结果为y2
print(x.grad) # 以x的值求导y2

tensor([[ 2.,  2.],
        [ 2.,  2.]])
tensor([[ 1.,  1.],
        [ 1.,  1.]])
