Begining in TensorFlow 
=====
TensorFlow 1.8.0

In [1]:
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from six.moves import xrange

import tensorflow as tf

sess = tf.InteractiveSession()
basic_shape = [2, 3]


/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
sess.run(tf.ones(shape=basic_shape, dtype=tf.int32, name='ones'))

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [3]:
sess.run(tf.fill(dims=basic_shape, value=1.0))

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [4]:
sess.run(tf.constant(value=1.0, dtype=tf.float32, shape=basic_shape))

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [5]:
print(sess.run(tf.random_normal(shape=basic_shape, mean=0.0, stddev=1.0, dtype=tf.float32)))
print(sess.run(tf.truncated_normal(shape=basic_shape, mean=0.0, stddev=1.0, dtype=tf.float32)))
print(sess.run(tf.random_uniform(shape=basic_shape, minval=1.0, maxval=2.0, dtype=tf.float32)))

[[-0.0288846  -0.573523   -0.8456304 ]
 [-0.30182928 -1.4425727  -1.5994556 ]]
[[-0.05848709  0.32487527  1.6713209 ]
 [ 0.5351735  -1.9378558   0.46732825]]
[[1.6961192 1.6135714 1.4693763]
 [1.4600254 1.9216795 1.6040583]]


In [6]:
tf.get_variable(name='weight', dtype=tf.float32, initializer=1.0)

<tf.Variable 'weight:0' shape=() dtype=float32_ref>

In [7]:
tensor = [[1, 2, 3], [4, 5, 6]]
sess.run(tf.shape(tensor))

array([2, 3], dtype=int32)

In [8]:
tensor = [1, 2, 3]
print(sess.run(tf.expand_dims(input=tensor, axis=0)))
print(sess.run(tf.expand_dims(input=tensor, axis=1)))
print(sess.run(tf.expand_dims(input=tensor, axis=-1)))

[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [9]:
x = [1, 1]
y = [2, 2]
z = [3, 3]
sess.run(tf.stack([x, y, z]))
sess.run(tf.stack([x, y, z]))

array([[1, 1],
       [2, 2],
       [3, 3]], dtype=int32)

In [10]:
x = [1, 1]
y = [2, 2]

print(sess.run(tf.concat(values=[x, y], axis=0)))
print(sess.run(tf.concat(values=[x, y], axis=-1)))

[1 1 2 2]
[1 1 2 2]


In [11]:
x = [1, 1]
y = [1, 2]

sess.run(tf.equal(x, y))

array([ True, False])

In [12]:
x = [1, 1, 0, 0]
sess.run(tf.cast(x, dtype=tf.bool))

array([ True,  True, False, False])

In [13]:
a = [[1, 2], [3, 4]]
b = [[1, 0], [0, 1]]
sess.run(tf.matmul(a, b))

array([[1, 2],
       [3, 4]], dtype=int32)

In [14]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
sess.run(tf.reshape(tensor=a, shape=[3, 3]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)